### ISSUE TITLE
Fails when plugin is activated but no pages contain `resize_to`

### ISSUE THREAD

**Issue by westonganger** [kubenstein/middleman-simple-thumbnailer#24]
Fails when plugin is activatedin `config.rb` but no pages in the project contain `resize_to`.

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/thumbnail20180504-1751-cit6am
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-simple-thumbnailer-1.3.1/lib/middleman-simple-thumbnailer/image_store.rb:27:in `initialize'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-simple-thumbnailer-1.3.1/lib/middleman-simple-thumbnailer/image_store.rb:27:in `open'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-simple-thumbnailer-1.3.1/lib/middleman-simple-thumbnailer/image_store.rb:27:in `each'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-simple-thumbnailer-1.3.1/lib/middleman-simple-thumbnailer/extension.rb:80:in `after_build'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extension.rb:479:in `block in bind_after_build'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/builder.rb:82:in `block in run!'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/builder.rb:81:in `run!'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/build.rb:80:in `block in build'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/build.rb:79:in `build'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:40:in `block in register'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /home/weston/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:70:in `<top (required)>'
  /home/weston/.rbenv/versions/2.4.1/bin/middleman:22:in `load'
  /home/weston/.rbenv/versions/2.4.1/bin/middleman:22:in `<top (required)>'
```

**Comment by ymph** [comment]
Thank you for your report,

Better late than never, it has been corrected.

regards.
